name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Change to your desired Node.js version

      - name: Install dependencies
        run: |
          cd src/currencyservice
          npm install

  build:
    runs-on: ubuntu-latest
    needs: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Ensure this matches the version in the node job

      - name: Build project
        run: |
          cd src/currencyservice
          npm run build # Optional, add if you have a build script
